#!/usr/bin/env Rscript
library(tidyverse)
library(geonames)
library(viridis)

####################################################
#  A: Define Functions                             #
####################################################
filter_box <- function(longitude, latitude, coords) {
  between(longitude, coords[1], coords[3]) &
    between(latitude, coords[2], coords[4]) &
    !is.na(longitude)
}

scale_this <- function(x){
  (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
}

# define a color pallette with maximal contrast
ancestry.colours <- c("A"="gold2", "B"="plum4","C"= "darkorange1", 
                      "D"="lightskyblue2", "E"="firebrick","F"= "burlywood3", "G"="gray51", 
                      "H"="springgreen4", "I"="lightpink2", "J"="deepskyblue4", "WHOLE_POPULATION"="black", 
                      "L"="mediumpurple4","M"= "orange","N"= "maroon","O"= "yellow3","P"= "brown4", 
                      "Q"="yellow4", "R"="sienna4", "S"="chocolate", "T"="gray19")

island_palette <- c("Kauai" = "#E69F00",
                    "Oahu" = "#56B4E9",
                    "Molokai" = "#009E73",
                    "Maui" = "#F0E442",
                    "Big Island" = "#D55E00")

substrate_palette <- c("Leaf litter" = "#E68FAC",
                       "Fruit/nut/veg" = "#0067A5",
                       "Flower" = "#DCD300",
                       "Fungus" = "#604E97",
                       "Compost" = "#F6A600",
                       "Other" = "#B3446C")

# hawaii strains
strain_islands <- c("XZ1514" = "#E69F00", "XZ1516" = "#E69F00","XZ1513" = "#E69F00","ECA372" = "#E69F00","ECA701" = "#E69F00","XZ1515" = "#E69F00",
                    "CB4856" = "#56B4E9",
                    "ECA369" = "#009E73","ECA738" = "#009E73",
                    "QX1792" = "#0072B2", "QX1794" = "#0072B2", "QX1793" = "#0072B2", "QX1791" = "#0072B2", "ECA740" = "#0072B2", "ECA741" = "#0072B2", "ECA363" = "#0072B2", "ECA743" = "#0072B2", "ECA742" = "#0072B2",
                    "ECA760" = "#CC79A7","ECA768" = "#CC79A7","ECA777" = "#CC79A7","ECA706" = "#CC79A7","ECA705" = "#CC79A7","ECA703" = "#CC79A7","ECA807" = "#CC79A7","ECA778" = "#CC79A7",
                    "ECA812" = "#CC79A7","ECA710" = "#CC79A7","ECA744" = "#CC79A7","ECA745" = "#CC79A7","ECA732" = "#CC79A7","ECA733" = "#CC79A7","ECA746" = "#CC79A7","DL238" = "#CC79A7",
                    "ECA347" = "#CC79A7","ECA730" = "#CC79A7","ECA724" = "#CC79A7","ECA722" = "#CC79A7","ECA189" = "#CC79A7","ECA191" = "#CC79A7","ECA723" = "#CC79A7","ECA712" = "#CC79A7",
                    "ECA396" = "#CC79A7")

# load strain names, generated by Figure7.R
sample_names <- sort(data.table::fread("data/ANNOTATE_VCF/samples.txt", header = F) %>% dplyr::pull(V1))

# load fulcrum cso df
load('data/fulcrum/df.Rda')

# process fulcrum data for variable tile plot 

if(!file.exists("data/fulcrum/HW_isotype_collection_parameters_processed.tsv")){
  # Filter cso to isolates assigned to an isotype
  hm_hi1 <- cso %>%
    dplyr::filter(!is.na(isotype)) %>%
    dplyr::select(isotype,
                  strain,
                  c_label,
                  s_label,
                  substrate,
                  island,
                  altitude,
                  latitude,
                  longitude,
                  ambient_temperature,
                  substrate_temperature,
                  ambient_humidity,
                  substrate_moisture)
  
  # load hawaii isolates found before hawaii 2017 trip
  old_hi_isolates <- googlesheets::gs_key("1V6YHzblaDph01sFDI8YK_fP0H7sVebHQTXypGdiQIjI") %>%
    googlesheets::gs_read("WI C. elegans") %>%
    dplyr::filter(isotype %in% names(strain_islands) & !(isotype %in% hm_hi1$isotype)) %>%
    dplyr::mutate(altitude = as.numeric(NA)) %>%
    dplyr::mutate(longitude = as.numeric(longitude),
                  substrate_temperature = substrate_temp,
                  ambient_temperature = ambient_temp)
  
  # join old and new hawaiian isolates
  hm_hi2 <- full_join(hm_hi1, old_hi_isolates)
  
  #set substrate to manuscript categories
  substrate_merge <- c("Fruit",
                       "Rotting fruit",
                       "Nut",
                       "Rotting nut",
                       "Rotting vegetable")
  
  hm_hi3 <- hm_hi2 %>% 
    dplyr::ungroup() %>%
    dplyr::mutate(substrate = ifelse(substrate %in% substrate_merge, "Fruit/nut/vegetable", substrate)) %>%
    dplyr::mutate(substrate = ifelse(substrate %in% c("Rotting fungus"), "Fungus", substrate)) %>%
    dplyr::mutate(substrate = ifelse(is.na(substrate), "Other", substrate)) %>%
    dplyr::mutate(fixed_substrate = ifelse(substrate == "Fruit/nut/vegetable", "Fruit/nut/veg",
                                           ifelse(substrate == "Rotting flower", "Flower",
                                                  ifelse(substrate == "Rotting fungus", "Fungus",
                                                         ifelse(substrate %in% c("Rotting wood",
                                                                                 "Rotting bark",
                                                                                 "Soil",
                                                                                 "Grass"), 
                                                                "Other",substrate))))) %>%
    dplyr::group_by(isotype) %>%
    dplyr::mutate(main_substrate = names(sort(summary(as.factor(fixed_substrate)), decreasing=T))[1]) %>% # find most common factor in group
    dplyr::ungroup()
  
  #set altitude from gps except for unknown collection locations
  options(geonamesUsername="katiesevans")
  options(geonamesHost="api.geonames.org")
  hm_hi4 <- hm_hi3 %>%
    dplyr::ungroup() %>%
    dplyr::rowwise() %>%
    dplyr::mutate(altitude = ifelse(is.na(altitude),
                                    geonames::GNsrtm3(latitude, longitude)$srtm3,
                                    altitude)
    ) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(altitude = ifelse(isotype %in% c("CB4856", "DL238"), NA, altitude))
  
  #set islands from gps
  hm_hi4$island <- "?"
  hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-158.3617,21.1968,-157.5117,21.7931)), "island"] <- "Oahu"
  hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-159.9362, 21.6523, -159.1782, 22.472)), "island"] <- "Kauai"
  hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-157.327, 21.0328, -156.685, 21.2574)), "island"] <- "Molokai"
  hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-156.7061, 20.4712, -155.9289, 21.0743)), "island"] <- "Maui"
  hm_hi4[filter_box(hm_hi4$longitude, hm_hi4$latitude, c(-156.1346, 18.6619, -154.6985, 20.4492)), "island"] <- "Big Island"
  
  # Identify most common island for isotypes
  hm_hi5 <- hm_hi4 %>%
    dplyr::group_by(isotype) %>%
    dplyr::mutate(main_island = names(sort(summary(as.factor(island)), decreasing=T))[1]) %>%
    dplyr::ungroup()
  
  # Identify mean values for continous variables for isotypes
  hm_hi6 <- hm_hi5 %>%
    dplyr::group_by(isotype) %>%
    dplyr::summarise_if(is.numeric, funs(mean), na.rm = TRUE) %>%
    dplyr::select(isotype,
                  altitude,
                  ambient_temperature,
                  substrate_temperature,
                  ambient_humidity,
                  substrate_moisture) %>%
    dplyr::ungroup()
  
  # Combine isotype data for plotting continous data
  hm_hi_proc <- full_join(hm_hi5 %>% dplyr::select(isotype, strain, main_island, main_substrate), hm_hi6) %>%
    dplyr::distinct(isotype, .keep_all = TRUE) %>%
    dplyr::select(-strain) %>%
    dplyr::mutate(altitude_s = scale_this(altitude),
                  ambient_temperature_s = scale_this(ambient_temperature),
                  substrate_temperature_s = scale_this(substrate_temperature),
                  ambient_humidity_s = scale_this(ambient_humidity),
                  substrate_moisture_s = scale_this(substrate_moisture)) %>%
    tidyr::gather(trait, value, -isotype)
  
  write.table(hm_hi_proc, file = "data/fulcrum/HW_isotype_collection_parameters_processed.tsv",
              col.names = T, quote = F, row.names = F, sep = "\t")
} else {
  hm_hi_proc <- data.table::fread("data/fulcrum/HW_isotype_collection_parameters_processed.tsv")
}

# load in wi strain info for lat long coordinates for map
df <- data.table::fread("data/WI_strain_list.csv")



# generate K summary plot - Supplemental figure XX
admixture_panel <- list()
for(kpops in 1:length(grep(".Q", list.files("data/ADMIXTURE/BEST_K/"), value = T))){
  K <- as.numeric(strsplit(grep(".Q", list.files("data/ADMIXTURE/BEST_K/"), value = T)[kpops], split = "\\.")[[1]][4])
  
  # load Q files
  qfile_name <- grep(pattern = glue::glue("{K}\\.Q$"), value = T, x = list.files("data/ADMIXTURE/BEST_K/"))
  qfile <- pophelper::readQ(files = paste0("data/ADMIXTURE/BEST_K/",qfile_name))[[1]]
  # add pop names
  colnames(qfile) <- LETTERS[1:K]
  
  # make long and determin order of plotting
  long_admix_pops <- qfile %>%
    dplyr::mutate(samples = sample_names) %>%
    dplyr::filter(samples %in% names(strain_islands)) %>%
    tidyr::gather(cluster, frac_cluster, -samples) %>%
    dplyr::group_by(samples) %>%
    dplyr::mutate(max_frac = max(frac_cluster)) %>%
    dplyr::ungroup() %>%
    dplyr::arrange(cluster, max_frac) %>%
    dplyr::mutate(samples = factor(samples, levels = unique(samples)))
  
  # establish plot order of strains based on anc pop and max fraction
  plot_order <- long_admix_pops %>%
    dplyr::filter(frac_cluster == max_frac) %>%
    dplyr::arrange(cluster, -max_frac) %>%
    dplyr::mutate(samples = factor(samples, levels = unique(samples)))
  
  temp_admix_plot <- long_admix_pops %>%
    dplyr::mutate(ordered_samples = factor(samples, levels = plot_order$samples)) %>%
    ggplot() +
    geom_bar(stat = "identity", 
             aes(x = ordered_samples, 
                 y = frac_cluster, 
                 fill = cluster)) +
    scale_fill_manual(values = ancestry.colours) +
    labs(fill = "", x = "", y =  glue::glue("K = {K}")) +
    theme_bw() +
    theme(axis.text.x=element_blank(),    
          axis.text.y=element_blank(),
          axis.title.y = element_text(angle = 0, vjust = .5),
          axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          panel.background=element_blank(),
          panel.border=element_blank(),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.background=element_blank(),
          plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  admix_plot_no_legend <- temp_admix_plot +
    theme(legend.position="none",
          axis.line=element_blank(),
          plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  grid::grid.newpage()
  admix_legend <- cowplot::get_legend(temp_admix_plot)
  grid::grid.draw(admix_legend) +
    theme(plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  # plot continous variables on heat map
  temp_hm_plot <- hm_hi_proc %>%
    dplyr::mutate(ordered_samples = factor(isotype, levels = plot_order$samples)) %>%
    dplyr::filter(trait %in% c("altitude_s",
                               "ambient_temperature_s",
                               "substrate_temperature_s",
                               "ambient_humidity_s",
                               "substrate_moisture_s")) %>%
    ggplot(.) +
    aes(x = ordered_samples, y = trait, fill = as.numeric(value)) +
    geom_tile(aes(x = ordered_samples, y = trait, fill = as.numeric(value))) +
    theme_bw() + 
    scale_fill_viridis(name="") +
    coord_equal() +
    theme_bw() +
    theme(axis.line=element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1),
          axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          panel.background=element_blank(),
          panel.border=element_blank(),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.background=element_blank(),
          plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  hm_plot_no_legend <- temp_hm_plot +
    theme(legend.position="none",
          plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  hm_plot_legend <- cowplot::get_legend(temp_hm_plot)
  
  # 2 
  # plot discrete variable, island, substrate
  temp_sub_plot <- hm_hi_proc %>%
    dplyr::mutate(ordered_samples = factor(isotype, levels = plot_order$samples)) %>% 
    dplyr::filter(trait == "main_substrate") %>%
    dplyr::mutate(value = factor(value, levels=names(substrate_palette))) %>%
    ggplot() +
    geom_tile(aes(x = ordered_samples, y = trait, fill = value)) + #factor(value, levels=names(substrate_palette))
    theme_bw() + 
    coord_equal() +
    labs(fill="") +
    scale_fill_manual(values = substrate_palette) +
    theme(axis.line=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          panel.background=element_blank(),
          panel.border=element_blank(),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.background=element_blank(),
          plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  sub_plot_no_legend <- temp_sub_plot +
    theme(legend.position="none",
          plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  sub_plot_legend <- cowplot::get_legend(temp_sub_plot)
  
  #3
  # plot islands
  temp_isl_plot <- hm_hi_proc %>%
    dplyr::mutate(ordered_samples = factor(isotype, levels = plot_order$samples)) %>% 
    dplyr::filter(trait == "main_island") %>%
    dplyr::mutate(value = factor(value, levels=names(island_palette))) %>%
    ggplot() +
    geom_tile(aes(x = ordered_samples, y = trait, fill = value)) +
    theme_bw() + 
    coord_equal() +
    labs(fill="") +
    scale_fill_manual(values=island_palette) +
    theme(axis.line=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          panel.background=element_blank(),
          panel.border=element_blank(),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.background=element_blank(),
          plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  isl_plot_no_legend <- temp_isl_plot +
    theme(legend.position="none",
          plot.margin = unit(c(0,0,0,0), units = "cm"))
  
  isl_plot_legend <- cowplot::get_legend(temp_isl_plot)

  #4
  # add all together
  admixture_panel[[kpops]] <- cowplot::plot_grid(admix_plot_no_legend,
                                        admix_legend,
                                        isl_plot_no_legend,
                                        isl_plot_legend,
                                        sub_plot_no_legend,
                                        sub_plot_legend,
                                        hm_plot_no_legend,
                                        hm_plot_legend,
                                        ncol = 2, nrow = 4,
                                        rel_heights = c(.8, .5, .5, 1),
                                        rel_widths = c(1, .2),
                                        align = "vh",
                                        axis = 'l')
  
  ggsave(admixture_panel[[kpops]], filename = glue::glue("plots/K{K}_Admix_plus_substrates.pdf"),
         width = 20, height = 10)
  
  strain_pops <- dplyr::filter(long_admix_pops, frac_cluster == max_frac) %>%
    dplyr::rename(strain=samples)
  
  isolation_info <- df %>%
    dplyr::filter(reference_strain == 1)%>%
    dplyr::select(strain = isotype, long = longitude, lat = latitude, state,country)%>%
    dplyr::filter(lat != "None")%>%
    dplyr::left_join(strain_pops,.,by="strain")%>%
    dplyr::filter(!is.na(lat))
  
  isolation_info$lat <- as.numeric(isolation_info$lat)
  isolation_info$long <- as.numeric(isolation_info$long)
  
  dev.off()
  world <- map_data("world")
  world <- world[world$region != "Antarctica",] # intercourse antarctica
  
  world_plot <- ggplot()+ geom_map(data=world, map=world,
                                   aes(x=long, y=lat, map_id=region),
                                   color="black", fill="#7f7f7f", size=0.5)+
    scale_fill_manual(values = ancestry.colours,name = "Population")+
    theme_map()+
    geom_label_repel(aes(long, lat, label = strain, fill = cluster),
                     data=dplyr::filter(isolation_info, state == "Hawaii"),
                     fontface = 'bold', color = 'white',
                     segment.color = 'cyan')+
    theme(legend.position = "none")+
    coord_cartesian(xlim = c(-160,-155), ylim = c(19,22.3))
  
  ggsave(world_plot, filename = glue::glue("plots/K{K}_HW_MAP_Admix.pdf"),
         height = 10,
         width = 10)
  
}
 



